modules/admin/controllers/ArticleController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Article;
use app\models\ArticleSearch;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article();
        $model->weight = 5;
        $model->FillBlankImg();

        if ($model->load(Yii::$app->request->post())) {

            $model->file = UploadedFile::getInstance($model, 'file');
            if($model->file){
                $model->dropOldImg();
                $file_name = uniqid();
                $model->img = $file_name . '.' . $model->file->extension;
                if (!$model->file->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->file->extension)){
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->file = null;
            }
            $model->image = UploadedFile::getInstance($model, 'image');
            if($model->image){
                $model->dropOldImg2();
                $file_name = uniqid();
                $model->imgFooter = $file_name . '.' . $model->image->extension;
                if (!$model->image->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->image->extension)){
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->image = null;
            }
            $model->image_radius = UploadedFile::getInstance($model, 'image_radius');
            if ($model->image_radius) {
                $model->dropOldImg();
                $file_name = uniqid();
                $model->img_radius = $file_name . '.' . $model->image_radius->extension;
                if (!$model->image_radius->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->image_radius->extension)) {
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->image_radius = null;
            }
            $model->preview_img = UploadedFile::getInstance($model, 'preview_img');
            if ($model->preview_img) {
                $model->dropOldImg4();
                $file_name = uniqid();
                $model->preview_image = $file_name . '.' . $model->preview_img->extension;
                if (!$model->preview_img->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->preview_img->extension)) {
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->preview_img = null;
            }


            $model->save();
            return $this->redirect('index');
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->file = UploadedFile::getInstance($model, 'file');
            if($model->file){
                $model->dropOldImg();
                $file_name = uniqid();
                $model->img = $file_name . '.' . $model->file->extension;

                if (!$model->file->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->file->extension)){
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->file = null;
            }
            $model->image = UploadedFile::getInstance($model, 'image');
            if($model->image){
                $model->dropOldImg2();
                $file_name = uniqid();
                $model->imgFooter = $file_name . '.' . $model->image->extension;
                if (!$model->image->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->image->extension)){
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->image = null;
            }
            $model->image_radius = UploadedFile::getInstance($model, 'image_radius');
            if ($model->image_radius) {
                $model->dropOldImg3();
                $file_name = uniqid();
                $model->img_radius = $file_name . '.' . $model->image_radius->extension;
                if (!$model->image_radius->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->image_radius->extension)) {
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->image_radius = null;
            }
            $model->preview_img = UploadedFile::getInstance($model, 'preview_img');
            if ($model->preview_img) {
                $model->dropOldImg4();
                $file_name = uniqid();
                $model->preview_image = $file_name . '.' . $model->preview_img->extension;
                if (!$model->preview_img->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->preview_img->extension)) {
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->preview_img = null;
            }

            if($model->save()){
                return $this->redirect('index');
            }else{
                VarDumper::dump($model->getErrors(),11,1);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->dropOldImg();
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionDeleteImg()
    {
        if(Yii::$app->request->post()){
            $id = Yii::$app->request->post('id');
            $this->findModel($id)->dropOldImg();
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionDeleteImg2()
    {
        if(Yii::$app->request->post()){
            $id = Yii::$app->request->post('id');
            $this->findModel($id)->dropOldImg2();
        }

        return $this->redirect(Yii::$app->request->referrer);
    }
    public function actionDeleteImg3()
    {
        if(Yii::$app->request->post()){
            $id = Yii::$app->request->post('id');
            $this->findModel($id)->dropOldImg3();
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionDeleteImg4()
    {
        if(Yii::$app->request->post()){
            $id = Yii::$app->request->post('id');
            $this->findModel($id)->dropOldImg4();
        }

        return $this->redirect(Yii::$app->request->referrer);
    }


    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/admin/controllers/VideoController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Video;
use app\models\VideoSearch;
use yii\db\Exception;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * VideoController implements the CRUD actions for Video model.
 */
class VideoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Video models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VideoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Video model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Video model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Video();
        $model->weight = 5;
        $model->FillBlankImg();

        if ($model->load(Yii::$app->request->post())) {

            $model->file = UploadedFile::getInstance($model, 'file');
            if($model->file){
                $model->dropOldImg();
                $file_name = uniqid();
                $model->img = $file_name . '.' . $model->file->extension;
                if (!$model->file->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->file->extension)){
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->file = null;

            }
            $model->image_radius = UploadedFile::getInstance($model, 'image_radius');
            if ($model->image_radius) {
                $model->dropOldImg3();
                $file_name = uniqid();
                $model->img_radius = $file_name . '.' . $model->image_radius->extension;
                if (!$model->image_radius->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->image_radius->extension)) {
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->image_radius = null;
            }

            $model->save();
            return $this->redirect('index');

        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Video model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->init();

        if ($model->load(Yii::$app->request->post())) {
            $model->file = UploadedFile::getInstance($model, 'file');
            if($model->file){
                $model->dropOldImg();
                $file_name = uniqid();
                $model->img = $file_name . '.' . $model->file->extension;
                if (!$model->file->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->file->extension)){
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->file = null;
            }
            $model->image_radius = UploadedFile::getInstance($model, 'image_radius');
            if ($model->image_radius) {
                $model->dropOldImg3();
                $file_name = uniqid();
                $model->img_radius = $file_name . '.' . $model->image_radius->extension;
                if (!$model->image_radius->saveAs(Yii::getAlias('@abs_path_to_uploads') . '/' . $file_name . '.' . $model->image_radius->extension)) {
                    throw new \RuntimeException('Ошибка сохранения файла');
                }
                $model->image_radius = null;
            }

            $model->save();
            return $this->redirect('index');
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Video model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->dropOldImg();
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionDeleteImg()
    {
        if(Yii::$app->request->post()){
            $id = Yii::$app->request->post('id');
            $this->findModel($id)->dropOldImg();
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Finds the Video model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Video the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Video::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/admin/views/video/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Level;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Video */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="video-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'level_id')->dropDownList(ArrayHelper::map(Level::find()->asArray()->orderBy('id')->all(), 'id', 'name')) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'type',
        ['template' => '{label}<div class="">{input}{hint} {error}</div>']
    )
        ->radioList(
            $model->types,
            [
                'item' => function ($index, $label, $name, $checked, $value) {
                    return '<label class="btn btn-white btn-info btn-round' . ($checked ? " active" : null) . ' ">' . Html::radio($name, $checked, ['value' => $value, 'autocomplete' => 'off']) . $label . '</label>';
                },
                'tag' => 'div', // this is by default
                'class' => 'btn-group',
                'data-toggle' => 'buttons',
            ]
        )->label(false) ?>

    <?= $form->field($model, 'description', [
        'template' => "<div>{input}\n<div class=\"error\">{error}</div></div>",
    ])->widget(\zxbodya\yii2\tinymce\TinyMce::className(), [
        'options' => ['rows' => 15, 'style' => 'margin-top:5vw'],
        'language' => 'ru',
//        'spellcheckerUrl'=>'http://speller.yandex.net/services/tinyspell',
        'fileManager' => [
            'class' => \zxbodya\yii2\elfinder\TinyMceElFinder::className(),
            'connectorRoute' => 'el-finder/connector',
        ],
    ]); ?>

    <?= $form->field($model, 'code')->textInput() ?>

    <?php if ($model->img) { ?>
        <?= Html::img(Yii::getAlias('@rel_path_to_uploads') . '/' . $model->img, ['class' => 'profile_foto']); ?>
        <div class="del_link">
            <?php
            if ($model->img != 'blank.jpg'){
                echo Html::a('Удалить', ['video/delete-img'], [
                    'data-method' => 'POST',
                    'data-params' => [
                        'id' => $model->id,
                    ],
                ]);
            }
            ?>
        </div>
    <?php } ?>

    <?php
    if (!$model->img){
        echo Html::img('/uploads/blank.jpg', ['class' => 'profile_foto']);
    }
    ?>


    <?= $form->field($model, 'file')->fileInput(['onchange'=>'readURL(this);']); ?>

    <?php if ($model->img_radius) { ?>
        <?= Html::img(Yii::getAlias('@rel_path_to_uploads') . '/' . $model->img_radius, ['class' => 'profile_foto']); ?>
        <div class="del_link">
            <?php
            if ($model->img_radius != 'blank.jpg') {
                echo Html::a('Удалить', ['article/delete-img'], [
                    'data-method' => 'POST',
                    'data-params' => [
                        'id' => $model->id,
                    ],
                ]);
            }
            ?>
        </div>
    <?php } ?>

    <?php
    if (!$model->img_radius) {
        echo Html::img('/uploads/blank.jpg', ['class' => 'profile_foto']);
    }
    ?>


    <?= $form->field($model, 'image_radius')->fileInput(['onchange' => 'readURL(this);']); ?>

    <?= $form->field($model, 'timer')->textInput() ?>

    <?= $form->field($model, 'points')->textInput() ?>

    <?= $form->field($model, 'weight')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Сохранить' : 'Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/video/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\VideoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="video-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'level_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'img') ?>

    <?php // echo $form->field($model, 'timer') ?>

    <?php // echo $form->field($model, 'points') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/video/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Video */

$this->title = 'Добавить видео';
$this->params['breadcrumbs'][] = ['label' => 'Videos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="video-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/video/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\VideoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Видео';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="video-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Добавить видео', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

          //  'id',
            'level_id',
            'name',
           // 'description',
            [
                'label' => 'Картинка',
                'format' => 'raw',
                'value' => function($data){
                    return Html::img(Yii::getAlias('@rel_path_to_uploads') . '/' . $data->img,[
                        'alt'=>'yii2 - картинка в gridview',
                        'style' => 'width:150px;'
                    ]);
                },
            ],
             'timer',
             'points',

            [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{update}&nbsp;{delete}'
            ],
        ],
    ]); ?>
</div>

modules/admin/views/video/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Video */

$this->title = 'Редактировать видео: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Videos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Сохранить';
?>
<div class="video-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/video/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Video */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Videos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="video-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Удалить видео?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            'level_id',
            'name',
            'description',
            'img',
            'timer',
            'points',
        ],
    ]) ?>

</div>